const fs=require('fs'),path=require('path'),os=require('os');
const CONFIG=process.argv[2]||path.join(__dirname,'agent-config.json');let cfg=JSON.parse(fs.readFileSync(CONFIG,'utf8'));const VERSION='0.1.0',sleep=ms=>new Promise(r=>setTimeout(r,ms));
const save=()=>{fs.writeFileSync(CONFIG+'.tmp',JSON.stringify(cfg,null,2));fs.renameSync(CONFIG+'.tmp',CONFIG)};
const norm=p=>path.resolve(String(p||''));const allowed=p=>(cfg.allowedRoots||[]).some(r=>{const a=norm(r),b=norm(p);return b===a||b.startsWith(a+path.sep)});
async function req(p,o){o=o||{};const h={'content-type':'application/json'};if(cfg.agentToken)h.authorization='Bearer '+cfg.agentToken;if(o.bootstrap)h['x-bootstrap-key']=cfg.bootstrapKey;const r=await fetch(cfg.relayUrl+p,{method:o.method||'GET',headers:h,body:o.body?JSON.stringify(o.body):undefined,signal:AbortSignal.timeout(o.timeout||20000)});const t=await r.text();let j={};try{j=JSON.parse(t)}catch{j={raw:t}}if(!r.ok)throw Error(r.status+' '+(j.error||t));return j}
async function register(){const b={deviceId:cfg.deviceId,name:cfg.name||os.hostname(),platform:process.platform,version:VERSION,meta:{arch:process.arch,release:os.release()}};const j=await req('/agent/register',{method:'POST',bootstrap:true,body:b});cfg.agentToken=j.agentToken;delete cfg.bootstrapKey;save()}
function diskInfo(){const roots=cfg.allowedRoots||[];return roots.map(r=>{try{const s=fs.statfsSync(r);return{root:r,total:s.blocks*s.bsize,free:s.bavail*s.bsize}}catch(e){return{root:r,error:e.message}}})}
async function execute(c){const a=c.args||{};try{
if(c.action==='system_status')return{ok:true,output:JSON.stringify({hostname:os.hostname(),platform:process.platform,release:os.release(),arch:process.arch,uptimeSeconds:os.uptime(),loadavg:os.loadavg(),totalMem:os.totalmem(),freeMem:os.freemem(),disks:diskInfo()},null,2)};
if(c.action==='read_file'){if(!allowed(a.path))throw Error('path not allowed');const b=fs.readFileSync(a.path),m=Math.min(a.max_bytes||1000000,1500000);return{ok:true,output:b.subarray(0,m).toString('utf8')+(b.length>m?'\n[TRUNCATED]':'')}}
if(c.action==='write_file'){if(!allowed(a.path))throw Error('path not allowed');fs.mkdirSync(path.dirname(a.path),{recursive:true});fs.writeFileSync(a.path,a.content,{encoding:'utf8',flag:a.mode==='append'?'a':'w'});return{ok:true,output:'written'}}
if(c.action==='list_dir'){if(!allowed(a.path))throw Error('path not allowed');const x=fs.readdirSync(a.path,{withFileTypes:true}).slice(0,2000).map(v=>({name:v.name,type:v.isDirectory()?'dir':v.isFile()?'file':'other'}));return{ok:true,output:JSON.stringify(x,null,2)}}
if(c.action==='http_check'){const r=await fetch(a.url,{method:'GET',redirect:'follow',signal:AbortSignal.timeout(Math.min(a.timeout_ms||10000,30000))});return{ok:r.ok,output:JSON.stringify({status:r.status,statusText:r.statusText,url:r.url})}}
if(c.action==='trigger'){if(!(cfg.allowedTriggers||[]).includes(a.name))throw Error('trigger not allowed');const d=cfg.triggerDir;if(!d)throw Error('triggerDir missing');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(d,a.name+'.trigger'),new Date().toISOString());return{ok:true,output:'triggered '+a.name}}
return{ok:false,error:'unknown action',output:''}}catch(e){return{ok:false,error:String(e.message||e),output:''}}}
async function beat(){await req('/agent/heartbeat',{method:'POST',body:{deviceId:cfg.deviceId,version:VERSION,meta:{arch:process.arch,release:os.release(),uptime:os.uptime()}}})}
async function poll(){const j=await req('/agent/poll?deviceId='+encodeURIComponent(cfg.deviceId),{timeout:25000});if(!j.command)return;const o=await execute(j.command);await req('/agent/result',{method:'POST',body:{deviceId:cfg.deviceId,commandId:j.command.id,ok:o.ok,output:o.output||'',error:o.error||null}})}
(async()=>{while(true){try{if(!cfg.agentToken)await register();await beat();for(let i=0;i<5;i++){await poll();await sleep((cfg.pollSeconds||2)*1000)}}catch(e){console.error(new Date().toISOString(),e.message);await sleep(5000)}}})().catch(e=>{console.error(e);process.exit(1)});