const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),cp=require('child_process');const{URL}=require('url');const fleet=require('./fleet');
const HOST='127.0.0.1',PORT=8794,PUBLIC='https://rdcommander.45-67-52-109.sslip.io',RESOURCE=PUBLIC+'/mcp',STATE=path.join(__dirname,'state.json'),PINHASH=path.join(__dirname,'owner-pin.sha256'),DEVICE='fxut9332680',SCOPES=['rd.read','rd.write','rd.exec'];
const sha=x=>crypto.createHash('sha256').update(String(x)).digest('hex'),rnd=n=>crypto.randomBytes(n||32).toString('base64url');
function load(){try{return JSON.parse(fs.readFileSync(STATE,'utf8'))}catch{return{clients:{},codes:{},access:{},refresh:{}}}}function save(x){const t=STATE+'.tmp';fs.writeFileSync(t,JSON.stringify(x,null,2));fs.renameSync(t,STATE)}
function J(res,n,o,h){res.writeHead(n,Object.assign({'content-type':'application/json; charset=utf-8','cache-control':'no-store'},h||{}));res.end(JSON.stringify(o))}function H(res,n,b){res.writeHead(n,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(b)}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>{d+=c;if(d.length>2000000){no(new Error('body too large'));req.destroy()}});req.on('end',()=>ok(d));req.on('error',no)})}function form(x){return Object.fromEntries(new URLSearchParams(x))}
function prune(x){const n=Date.now();for(const q of['codes','access','refresh'])for(const k of Object.keys(x[q]||{}))if(x[q][k].exp<n)delete x[q][k]}
function bearer(req){const m=String(req.headers.authorization||'').match(/^Bearer\s+(.+)$/i);return m?m[1]:null}function auth(req,scope){const x=load(),r=x.access[sha(bearer(req)||'')];return r&&r.exp>Date.now()&&r.aud===RESOURCE&&String(r.scope||'').split(/\s+/).includes(scope)?r:null}
function challenge(scope){return 'Bearer resource_metadata="'+PUBLIC+'/.well-known/oauth-protected-resource", error="insufficient_scope", error_description="RD Commander authorization required: '+scope+'"'}
function sec(s){return[{type:'oauth2',scopes:[s]}]}function tools(){const r=sec('rd.read'),w=sec('rd.write'),e=sec('rd.exec');return[
{name:'rd_profile',title:'RD Commander Profile',description:'Show the authorized RD Commander owner profile.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r,'openai/profile':true}},
{name:'rd_system_status',title:'System Status',description:'Read system and RD Commander status for fxut9332680, including the authorized RD fleet inventory.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r}},
{name:'rd_list_directory',title:'List Directory',description:'List a Windows directory locally, or use path rd:<device_id>:C:\\path for a fleet device.',inputSchema:{type:'object',properties:{path:{type:'string'}},required:['path'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r}},
{name:'rd_read_file',title:'Read File',description:'Read a UTF-8 text file locally, or use path rd:<device_id>:C:\\path for a fleet device.',inputSchema:{type:'object',properties:{path:{type:'string'},max_bytes:{type:'integer',minimum:1,maximum:1500000}},required:['path'],additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r}},
{name:'rd_write_file',title:'Write File',description:'Write or append a UTF-8 file locally, or use path rd:<device_id>:C:\\path for a fleet device.',inputSchema:{type:'object',properties:{path:{type:'string'},content:{type:'string'},mode:{type:'string',enum:['rewrite','append']}},required:['path','content'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false},securitySchemes:w,_meta:{securitySchemes:w}},
{name:'rd_execute_command',title:'Execute Command',description:'Execute locally, or prefix command with rd:<device_id>:: to execute on an authorized fleet device. This can change system state.',inputSchema:{type:'object',properties:{command:{type:'string'},shell:{type:'string',enum:['powershell','cmd']},timeout_ms:{type:'integer',minimum:1000,maximum:120000}},required:['command'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true},securitySchemes:e,_meta:{securitySchemes:e}}
,
{name:'rd_fleet_status',title:'Fleet Status',description:'Read RD Commander relay health and controller authorization status.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r}},
{name:'rd_fleet_devices',title:'Fleet Devices',description:'List RD Commander devices registered on the authorized relay.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false},securitySchemes:r,_meta:{securitySchemes:r}}]}
function pth(p){const x=path.resolve(String(p||''));if(!/^[A-Za-z]:\\/.test(x))throw Error('absolute Windows path required');return x}
function rdspec(v){const m=String(v||'').match(/^rd:([^:]+):(.*)$/s);return m?{device_id:m[1],value:m[2]}:null}
function b64u16(v){return Buffer.from(String(v||''),'utf16le').toString('base64')}
function psu16(b){return "[Text.Encoding]::Unicode.GetString([Convert]::FromBase64String('"+b+"'))"}
function run(c,s,t){return new Promise(ok=>{t=Math.max(1000,Math.min(Number(t)||30000,120000));let exe,args;if(s==='cmd'){exe=process.env.ComSpec||'cmd.exe';args=['/d','/s','/c',c]}else{exe='powershell.exe';args=['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',c]}cp.execFile(exe,args,{timeout:t,maxBuffer:1500000,windowsHide:true},(e,a,b)=>ok({ok:!e,stdout:String(a||'').slice(0,1500000),stderr:String(b||'').slice(0,1500000),error:e?String(e.message||e):null,code:e&&Number.isInteger(e.code)?e.code:0}))})}
async function call(n,a){a=a||{};if(n==='rd_profile'){const v={id:'rdc-owner',name:'RD Commander Owner',device:DEVICE};return{content:[{type:'text',text:JSON.stringify(v)}],structuredContent:v,isError:false}}
if(n==='rd_system_status'){let d={};try{const z=fs.statfsSync('C:\\');d={total:z.blocks*z.bsize,free:z.bavail*z.bsize}}catch(e){d={error:e.message}}let fl={configured:false,count:0,devices:[]};try{const q=await fleet.devices();const a=Array.isArray(q)?q:(Array.isArray(q.devices)?q.devices:[]);fl={configured:true,count:a.length,devices:a.map(x=>({id:x.id||x.device_id||x.deviceId||null,name:x.name||x.device_name||x.hostname||null,status:x.status||x.state||null,lastSeen:x.lastSeen||x.last_seen||null}))}}catch(e){fl={configured:false,count:0,devices:[],error:String(e.message||e)}}const v={device:DEVICE,hostname:os.hostname(),release:os.release(),arch:os.arch(),uptimeSeconds:Math.floor(os.uptime()),totalMem:os.totalmem(),freeMem:os.freemem(),diskC:d,mcp:{version:'1.2.0',port:PORT},fleet:fl};return{content:[{type:'text',text:JSON.stringify(v,null,2)}],structuredContent:v,isError:false}}
if(n==='rd_list_directory'){const r=rdspec(a.path);if(r){const pb=b64u16(r.value),cmd="$p="+psu16(pb)+"; Get-ChildItem -LiteralPath $p -Force | Select-Object Name,FullName,PSIsContainer,Length,LastWriteTime | ConvertTo-Json -Depth 3 -Compress";return await fleet.rpc('execute_command',{device_id:r.device_id,command:cmd,shell:'powershell',timeout_ms:30000})}const v=fs.readdirSync(pth(a.path),{withFileTypes:true}).slice(0,2000).map(x=>({name:x.name,type:x.isDirectory()?'dir':x.isFile()?'file':'other'}));return{content:[{type:'text',text:JSON.stringify(v,null,2)}],isError:false}}
if(n==='rd_read_file'){const r=rdspec(a.path);if(r){const pb=b64u16(r.value),cmd="$p="+psu16(pb)+"; Get-Content -LiteralPath $p -Raw -ErrorAction Stop";return await fleet.rpc('execute_command',{device_id:r.device_id,command:cmd,shell:'powershell',timeout_ms:30000})}const b=fs.readFileSync(pth(a.path)),m=Math.max(1,Math.min(Number(a.max_bytes)||500000,1500000));return{content:[{type:'text',text:b.subarray(0,m).toString('utf8')+(b.length>m?'\n[TRUNCATED]':'')}],isError:false}}
if(n==='rd_write_file'){const r=rdspec(a.path);if(r){const pb=b64u16(r.value),cb=b64u16(a.content||''),verb=a.mode==='append'?'Add-Content':'Set-Content',cmd="$p="+psu16(pb)+"; $c="+psu16(cb)+"; $d=Split-Path -Parent $p; if($d){New-Item -ItemType Directory -Force -Path $d|Out-Null}; "+verb+" -LiteralPath $p -Value $c -Encoding UTF8; Write-Output ('written '+$p)";return await fleet.rpc('execute_command',{device_id:r.device_id,command:cmd,shell:'powershell',timeout_ms:30000})}const p=pth(a.path);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,String(a.content||''),{encoding:'utf8',flag:a.mode==='append'?'a':'w'});return{content:[{type:'text',text:'written '+p}],isError:false}}
if(n==='rd_execute_command'){const m=String(a.command||'').match(/^rd:([^:]+)::([\s\S]*)$/);if(m)return await fleet.rpc('execute_command',{device_id:m[1],command:m[2],shell:a.shell==='cmd'?'cmd':'powershell',timeout_ms:Number(a.timeout_ms)||30000});const q=await run(String(a.command||''),a.shell==='cmd'?'cmd':'powershell',a.timeout_ms);return{content:[{type:'text',text:JSON.stringify(q,null,2)}],structuredContent:q,isError:!q.ok}}if(n==='rd_fleet_status'){const v=await fleet.health();return{content:[{type:'text',text:JSON.stringify(v,null,2)}],structuredContent:v,isError:!v.ok}}
if(n==='rd_fleet_devices'){const v=await fleet.devices();return{content:[{type:'text',text:JSON.stringify(v,null,2)}],structuredContent:v,isError:false}}throw Error('unknown tool')}
function scope(n){return n==='rd_write_file'?'rd.write':n==='rd_execute_command'?'rd.exec':'rd.read'}
async function mcp(req,res){let m;try{m=JSON.parse(await body(req)||'{}')}catch{return J(res,400,{jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}})}const id=m.id;if(m.method==='initialize')return J(res,200,{jsonrpc:'2.0',id,result:{protocolVersion:String((m.params||{}).protocolVersion||'2025-06-18'),capabilities:{tools:{listChanged:false}},serverInfo:{name:'RD Commander',version:'1.2.0'},instructions:'Owner-authorized VPS administration. Prefer inspection before changes.'}});if(m.method==='notifications/initialized'){res.writeHead(202);return res.end()}if(m.method==='ping')return J(res,200,{jsonrpc:'2.0',id,result:{}});if(m.method==='tools/list')return J(res,200,{jsonrpc:'2.0',id,result:{tools:tools()}});if(m.method==='tools/call'){const n=String((m.params||{}).name||''),sc=scope(n);if(!auth(req,sc))return J(res,200,{jsonrpc:'2.0',id,result:{content:[{type:'text',text:'RD Commander owner authorization required.'}],_meta:{'mcp/www_authenticate':[challenge(sc)]},isError:true}});try{return J(res,200,{jsonrpc:'2.0',id,result:await call(n,(m.params||{}).arguments)})}catch(e){return J(res,200,{jsonrpc:'2.0',id,result:{content:[{type:'text',text:String(e.message||e)}],isError:true}})}}return J(res,200,{jsonrpc:'2.0',id:id==null?null:id,error:{code:-32601,message:'Method not found'}})}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,PUBLIC);
if(u.pathname==='/health')return J(res,200,{ok:true,name:'RD Commander MCP',version:'1.2.0',device:DEVICE});
if(u.pathname==='/.well-known/oauth-protected-resource')return J(res,200,{resource:RESOURCE,authorization_servers:[PUBLIC],scopes_supported:SCOPES,bearer_methods_supported:['header']});
if(u.pathname==='/.well-known/oauth-authorization-server')return J(res,200,{issuer:PUBLIC,authorization_endpoint:PUBLIC+'/oauth/authorize',token_endpoint:PUBLIC+'/oauth/token',registration_endpoint:PUBLIC+'/oauth/register',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],scopes_supported:SCOPES,authorization_response_iss_parameter_supported:true});
if(u.pathname==='/oauth/register'&&req.method==='POST'){const b=JSON.parse(await body(req)||'{}'),r=Array.isArray(b.redirect_uris)?b.redirect_uris.filter(x=>/^https:\/\/chatgpt\.com\//.test(String(x))):[];if(!r.length)return J(res,400,{error:'invalid_redirect_uri'});const st=load(),cid='rdc_'+rnd(18);st.clients[cid]={redirect_uris:r,created:Date.now()};save(st);return J(res,201,{client_id:cid,redirect_uris:r,grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none'})}
if(u.pathname==='/oauth/authorize'&&req.method==='GET'){const q=Object.fromEntries(u.searchParams),st=load(),c=st.clients[q.client_id];if(!c||!c.redirect_uris.includes(q.redirect_uri)||q.code_challenge_method!=='S256'||!q.code_challenge)return H(res,400,'Invalid OAuth request.');const esc=x=>String(x||'').replace(/[&<>"']/g,z=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[z])),h=Object.entries(q).map(([k,v])=>'<input type="hidden" name="'+esc(k)+'" value="'+esc(v)+'">').join('');return H(res,200,'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>RD Commander</title><style>body{font-family:system-ui;background:#07111a;color:#eef7ff;display:grid;place-items:center;min-height:100vh}.c{width:min(500px,90vw);padding:28px;border:1px solid #2c4659;border-radius:18px;background:#0c1822}input,button{width:100%;box-sizing:border-box;padding:13px;margin-top:12px;border-radius:10px}input{background:#071018;color:white;border:1px solid #35536b}button{background:#38d39f;border:0;font-weight:800}</style><div class="c"><h1>RD Commander</h1><p>Authorize ChatGPT to use your VPS tools.</p><form method="post">'+h+'<input name="pin" inputmode="numeric" placeholder="Owner one-time PIN" required><button>Authorize ChatGPT</button></form></div>')}
if(u.pathname==='/oauth/authorize'&&req.method==='POST'){const q=form(await body(req)),st=load(),c=st.clients[q.client_id],ph=fs.existsSync(PINHASH)?fs.readFileSync(PINHASH,'utf8').trim():'';if(!c||!c.redirect_uris.includes(q.redirect_uri))return H(res,400,'Invalid OAuth client.');if(!ph||sha(q.pin)!==ph)return H(res,403,'Invalid owner PIN.');try{fs.unlinkSync(PINHASH)}catch{};try{fs.unlinkSync(path.join(__dirname,'owner-pin-once.txt'))}catch{};const code=rnd(32),sc=(q.scope||SCOPES.join(' ')).split(/\s+/).filter(x=>SCOPES.includes(x)).join(' ')||SCOPES.join(' ');st.codes[sha(code)]={client_id:q.client_id,redirect_uri:q.redirect_uri,challenge:q.code_challenge,scope:sc,aud:q.resource||RESOURCE,exp:Date.now()+300000};prune(st);save(st);const r=new URL(q.redirect_uri);r.searchParams.set('code',code);if(q.state)r.searchParams.set('state',q.state);r.searchParams.set('iss',PUBLIC);res.writeHead(302,{location:r.toString()});return res.end()}
if(u.pathname==='/oauth/token'&&req.method==='POST'){const q=form(await body(req)),st=load();prune(st);if(q.grant_type==='authorization_code'){const k=sha(q.code||''),r=st.codes[k];if(!r||r.client_id!==q.client_id||r.redirect_uri!==q.redirect_uri)return J(res,400,{error:'invalid_grant'});if(crypto.createHash('sha256').update(String(q.code_verifier||'')).digest('base64url')!==r.challenge)return J(res,400,{error:'invalid_grant'});delete st.codes[k];const a=rnd(32),f=rnd(40),n=Date.now();st.access[sha(a)]={scope:r.scope,aud:r.aud,exp:n+3600000};st.refresh[sha(f)]={client_id:r.client_id,scope:r.scope,aud:r.aud,exp:n+2592000000};save(st);return J(res,200,{access_token:a,token_type:'Bearer',expires_in:3600,refresh_token:f,scope:r.scope})}if(q.grant_type==='refresh_token'){const k=sha(q.refresh_token||''),r=st.refresh[k];if(!r||r.client_id!==q.client_id)return J(res,400,{error:'invalid_grant'});delete st.refresh[k];const a=rnd(32),f=rnd(40),n=Date.now();st.access[sha(a)]={scope:r.scope,aud:r.aud,exp:n+3600000};st.refresh[sha(f)]={client_id:r.client_id,scope:r.scope,aud:r.aud,exp:n+2592000000};save(st);return J(res,200,{access_token:a,token_type:'Bearer',expires_in:3600,refresh_token:f,scope:r.scope})}return J(res,400,{error:'unsupported_grant_type'})}
if(u.pathname==='/mcp'&&req.method==='POST')return mcp(req,res);if(u.pathname==='/mcp')return J(res,405,{error:'POST required'},{allow:'POST'});return J(res,404,{error:'not_found'})
}catch(e){return J(res,500,{error:'server_error',message:String(e.message||e)})}}).listen(PORT,HOST,()=>console.log('RD Commander MCP listening '+HOST+':'+PORT));